config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :description, presence: true, length: { minimum: 5, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
before_action :set_article, only: [:edit, :update, :show, :destroy]

  
  def index
    @article = Article.all
  end
  
  
  def new
    @article = Article.new
  end
  
  def edit
  end
  

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully saved"
      redirect_to article_path(@article)
    else
      render :new
    end
  end
  
    
  def update
    if @article.update(article_params)
      flash[:notice] = "Your article was successfully updated"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end
  
  
  def show
  end


  def destroy
    @article.destroy
    flash[:notice] = "This article was successfully deleeted"
    redirect_to articles_path
  end


  private
    def set_article
      @article = Article.find(params[:id])
    end
  
    def article_params
      params.require(:article).permit(:title, :description)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
  end
  
  def about 
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>These are an errors which appeared during creation an article</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %> <br/>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back to articles list', articles_path %>

app/views/articles/edit.html.erb
<h1>Some page for editing articles</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>here is a list of articles</h1>
<p>
  <%= link_to "Create a new article", new_article_path %>
</p>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  
  <% @article.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Show all', article_path(article) %></td>
    <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>
<p>
  <%= link_to 'Home', root_path %>
</p>

app/views/articles/new.html.erb
<h1>This is a new articles page</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Here is your title</h1>

<%= link_to 'Edit article', edit_article_path(@article) %>

<p>
  Title: <%= @article.title %>
</p>
<p>
  Description: <%= @article.description %>
</p>

<%= link_to 'Back to articles list', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstRubyProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/messages' %>
  <%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>this is some about page</h1>

<%=  link_to 'Home', root_path %>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>My page for ruby app</title>
        <link rel="stylesheet" type="text/css" href="home.css">
    </head>
    <body>
        <header class="header">
            <div class="container">
                <div class="header_items_outer">
                    <div class="container_img">
                        <img src="Ruby_logo.png">
                    </div>
                    <div class="container_text">
                        <h1>Keep calm and learn Ruby on Rails</h1>
                        <h2>It's a powerfull language with a huge community</h2>
                    </div>
                </div>
            </div>
        </header>
        <!-- start navigation menu -->
        <nav class="navigation">
            <div class="container">
                <ul>
                    <li><a>
                      <%=  link_to 'Home', root_path %>
                    </a></li>
                    <li><a>
                      <%=  link_to 'About Ruby', about_path %>
                    </a></li>
                    <li><a>
                      <%= link_to 'Articles', articles_path %>  
                    </a></li>             
                </ul>
                <!-- start login form -->
                <form class="login" action="#">
                    <input type="text" placeholder="login" required>
                    <input type="password" placeholder="password" required>
                    <input type="submit" value="sign in">
                </form>
                <!-- end login form -->
            </div>
        </nav>
        <!-- end navigation menu -->
        
        <!--start main page content -->
        <main>
            <div class="container">
                <h2 class="container_title">Some interesting articles <small>about Ruby</small></h2>
                <div class="articles_array">
                    <div class="article_outer">
                        <div class="article">
                            <h3>some article name</h3>
                            <img src="images/rails.jpeg">
                            <p>This guide is designed for beginners who want to get started with a Rails application from scratch. It does not assume that you have any prior experience with Rails. However, to get the most out of it, you need to have some prerequisites installed:</p>
                        </div>
                    </div>
                    <div class="article_outer">
                        <div class="article">
                            <h3>some article name</h3>
                            <img src="images/rails2.jpeg">
                            <p>Rails is a web application framework running on the Ruby programming language. If you have no prior experience with Ruby, you will find a very steep learning curve diving straight into Rails. There are several curated lists of online resources for learning Ruby</p>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!--end main page content -->
        
        <!-- start footer -->
        <footer class="footer">
            <div class="container">
                <p>Copyright All rights reserved</p>
                <p>My laboratory 2016</p>
            </div>
        </footer>
        <!-- end footer -->
    </body>
</html>